spring:
  application:
    name: config
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/imdangun/msa.home.git
          username: imdangun
          password: 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
          searchPaths: /prop, /prop/{application}
          clone-on-start: true

server:
  port: 8070