spring:
  application:
    name: config
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/imdangun/msa.home.git
          username: imdangun
          password: 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
          searchPaths: /config_repo, /config_repo/{application}
          clone-on-start: true

server:
  port: 8070