spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: license-service
          uri: lb://license
          predicates:
            - Path=/api/licenses/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway-Request, Gateway-Processed
            - AddResponseHeader=X-Gateway-Response, Gateway-Added
            - name: CircuitBreaker
              args:
                name: licenseCircuitBreaker

        - id: firm-service
          uri: lb://firm
          predicates:
            - Path=/api/firms/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway-Request, Gateway-Processed
            - AddResponseHeader=X-Gateway-Response, Gateway-Added
            - name: CircuitBreaker
              args:
                name: firmCircuitBreaker

        - id: license-with-firm-v2
          uri: lb://license
          predicates:
            - Path=/api/v2/licenses/**
          filters:
            - RewritePath=/api/v2/licenses/(?<segment>.*), /licenses/${segment}
server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8071/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info