spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/license
    username: license
    password: license
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true